# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Blog
tagline:          'by Ethan Burrell'
description:      'A blog made by me, Ethan Burrell, about the intersection of Machine Learning and Business'
url:              https://ethanburrell.github.io/blog/
baseurl:          https://ethanburrell.github.io/blog/

author:
  name:           'Ethan Burrell'
  url:            https://ethanburrell.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ethanburrell/blog

plugins:
  - jekyll-feed
