# Dependencies
highlighter:      rouge

# Permalinks
#permalink:        pretty
#permalink:        /:year/:month/:day/:title/

# Setup
title:            Blog
tagline:          'by Ethan Burrell'
description:      'A blog made by me, Ethan Burrell, about the intersection of Machine Learning and Business'
url:              https://ethanburrell.github.io
baseurl:          blog/

author:
  name:           'Ethan Burrell'
  url:            https://ethanburrell.github.io/blog/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ethanburrell/

plugins:
  - jekyll-feed
